from mobitic_utils.db import (
    export_grille,
    export_filosofi,
    export_JRC,
    export_total_population_to_db,
    export_devices_to_db,
    export_average_population_to_db,
    export_derivative_population_to_db,
    export_intraday_population_to_db,
    export_area_attraction,
    join_filosofi,
    export_active_mobiles_to_db,
    add_rescaled_columns,
)

EXPORT_CONFIG = [
    {
        "name": "active devices march 2019",
        "export": export_active_mobiles_to_db,
        "table": "active_devices",
        "force": False,
        "type": "export",
    },
    {
        "name": "grille",
        "export": export_grille,
        "table": "grille",
        "force": False,
        "type": "export",
    },
    {
        "name": "filosofi",
        "export": export_filosofi,
        "table": "filosofi",
        "force": False,
        "type": "export",
    },
    {
        "name": "jrc",
        "export": export_JRC,
        "table": "jrc",
        "force": False,
        "type": "export",
    },
    {
        "name": "total population",
        "export": export_total_population_to_db,
        "table": "total_population",
        "force": False,
        "type": "export",
    },
    {
        "name": "devices population",
        "export": export_devices_to_db,
        "table": "total_devices",
        "force": False,
        "type": "export",
    },
    {
        "name": "Area attraction 2020",
        "export": export_area_attraction,
        "table": "area_attraction",
        "force": False,
        "type": "export",
    },
    {
        "name": "join filosofi",
        "export": join_filosofi,
        "table 1": "total_population",
        "table 2": "filosofi",
        "column": "filosofi",
        "force": False,
        "type": "join",
    },
    {
        "name": "average population",
        "export": export_average_population_to_db,
        "table": "average_population",
        "force": False,
        "type": "export",
    },
    {
        "name": "derivative population",
        "export": export_derivative_population_to_db,
        "table": "derivative_population",
        "force": False,
        "type": "export",
    },
    {
        "name": "intraday population",
        "export": export_intraday_population_to_db,
        "table": "intraday_population",
        "force": False,
        "type": "export",
    },
]
